title: "Portfolio Ingénieur CFD"
description: "Portfolio de projets CFD, simulation numérique et analyse d’ingénierie."
url: "https://ramiboufedji-projets.github.io/"
baseurl: ""

author:
  name: "Rami Boufedji"
  email: "ramyboufedji@gmail.com"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
